# This is a config for E2B sandbox template.
# You can use template ID (rlecafwpjpj0ihrfjk1p) or template name (web-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("web-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("web-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('web-test')

team_id = "be28bd10-2dd3-46e7-ab16-46533bfcf0cb"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "web-test"
template_id = "rlecafwpjpj0ihrfjk1p"
